---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/bmi":
    get:
      summary: calculate bmi
      parameters:
      - name: id
        required: true
        description: Patient ID
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                Category: Obesity
                bmi: 262.385
                height: 1.05
                weight: 289.28
  "/bmr":
    post:
      summary: calculate bmr
      tags:
      - BMR
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                patient_id: 1
                formula: harris
                result: '2349.43913999999999'
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  formula:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                formula:
                  type: string
                  example: mifflin
                  description: Formula name lowercase
                id:
                  type: integer
                  example: 1
                  description: Patient Id
        required: true
    get:
      summary: history bmr
      tags:
      - BMR
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: integer
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                patient_id: 1
                formula_id: 1
                result: '75.0'
                calculated_on: '2024-11-03'
                created_at: '2025-09-27T20:41:47.483Z'
                updated_at: '2025-09-27T20:41:47.483Z'
  "/doctors":
    get:
      summary: list doctors
      tags:
      - Doctor
      parameters:
      - name: offset
        in: query
        required: false
        schema:
          type: number
      - name: limit
        in: query
        required: false
        schema:
          type: number
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                first_name: Skye
                last_name: Hackett
                middle_name: Hilll
                created_at: '2025-09-27T20:41:47.579Z'
                updated_at: '2025-09-27T20:41:47.579Z'
              - id: 2
                first_name: Dee
                last_name: Schulist
                middle_name: Becker
                created_at: '2025-09-27T20:41:47.584Z'
                updated_at: '2025-09-27T20:41:47.584Z'
              - id: 3
                first_name: Efrain
                last_name: Wyman
                middle_name: Bergstrom
                created_at: '2025-09-27T20:41:47.587Z'
                updated_at: '2025-09-27T20:41:47.587Z'
              - id: 4
                first_name: Retta
                last_name: Padberg
                middle_name: Goodwin
                created_at: '2025-09-27T20:41:47.592Z'
                updated_at: '2025-09-27T20:41:47.592Z'
              - id: 5
                first_name: Herman
                last_name: Moore
                middle_name: Abshire
                created_at: '2025-09-27T20:41:47.595Z'
                updated_at: '2025-09-27T20:41:47.595Z'
    post:
      summary: create doctor
      tags:
      - Doctor
      parameters: []
      responses:
        '201':
          description: Doctor created successfully
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                middle_name:
                  type: string
              required:
              - first_name
              - last_name
  "/doctors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show doctor
      tags:
      - Doctor
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 6
                first_name: Rocco
                last_name: Ankunding
                middle_name: McClure
                created_at: '2025-09-27T20:41:47.783Z'
                updated_at: '2025-09-27T20:41:47.783Z'
    put:
      summary: update doctor
      tags:
      - Doctor
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                first_name: Ana
                last_name: Hoeger
                middle_name: Jaskolski
                id: 6
                created_at: '2025-09-27T20:41:47.875Z'
                updated_at: '2025-09-27T20:41:47.875Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                middle_name:
                  type: string
  "/gender":
    get:
      summary: list genders
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                name: Female
                created_at: '2025-09-27T20:41:48.040Z'
                updated_at: '2025-09-27T20:41:48.040Z'
    post:
      summary: create gender
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                error: 'Error {name: ["Gender name already exists"]}'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gender:
                  type: string
              description: 'gender ex: Male'
  "/patients":
    get:
      summary: list patients
      parameters:
      - name: full_name
        in: query
        schema:
          type: string
      - name: gender
        in: query
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      tags:
      - Patients
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                first_name: Fermin
                last_name: Oberbrunner
                middle_name: Kshlerin
                gender_id: 1
                birthday: '2001-07-09'
                height: 183
                weight: '222.84'
                created_at: '2025-09-27T20:41:48.285Z'
                updated_at: '2025-09-27T20:41:48.285Z'
                full_name: fermin oberbrunner kshlerin
                doctors:
                - id: 1
                  first_name: Salvatore
                  last_name: Rempel
                  middle_name: Donnelly
                  created_at: '2025-09-27T20:41:48.289Z'
                  updated_at: '2025-09-27T20:41:48.289Z'
                - id: 2
                  first_name: Lakia
                  last_name: O'Conner
                  middle_name: O'Kon
                  created_at: '2025-09-27T20:41:48.293Z'
                  updated_at: '2025-09-27T20:41:48.293Z'
                gender:
                  id: 1
                  name: Female
                  created_at: '2025-09-27T20:41:48.281Z'
                  updated_at: '2025-09-27T20:41:48.281Z'
    post:
      summary: Create patient
      tags:
      - Patients
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    birthday:
                      type: string
                      format: date
                    height:
                      type: number
                    weight:
                      type: number
                    gender:
                      type: string
                    doctor_ids:
                      type: array
                      items:
                        type: integer
                  required:
                  - first_name
                  - last_name
                  - birthday
                  - height
                  - weight
                  - gender
  "/patients/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show patient
      tags:
      - Patients
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1
                first_name: Brent
                last_name: Streich
                middle_name: Schaefer
                gender_id: 1
                birthday: '1978-05-02'
                height: 84
                weight: '200.35'
                created_at: '2025-09-27T20:41:48.524Z'
                updated_at: '2025-09-27T20:41:48.524Z'
                full_name: brent streich schaefer
                doctors: []
                gender:
                  id: 1
                  name: Female
                  created_at: '2025-09-27T20:41:48.519Z'
                  updated_at: '2025-09-27T20:41:48.519Z'
    put:
      summary: update patient
      tags:
      - Patients
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1
                first_name: Иван
                last_name: Петров
                middle_name: Roberts
                gender_id: 1
                birthday: '1990-01-01'
                height: 180
                weight: '75.0'
                created_at: '2025-09-27T20:41:48.609Z'
                updated_at: '2025-09-27T20:41:48.623Z'
                full_name: иван петров roberts
                doctors: []
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
