---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/bmi":
    get:
      summary: calculate bmi
      parameters:
      - name: id
        required: true
        description: Patient ID
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                Category: Normal weight
                bmi: 23.834
                height: 0.94
                weight: 21.06
  "/bmr":
    post:
      summary: calculate bmr
      tags:
      - BMR
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                patient_id: 1
                formula: harris
                result: '3010.22237'
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  formula:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                formula:
                  type: string
                  example: mifflin
                  description: Formula name lowercase
                id:
                  type: integer
                  example: 1
                  description: Patient Id
        required: true
    get:
      summary: history bmr
      tags:
      - BMR
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: integer
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                patient_id: 1
                formula_id: 1
                result: '48.0'
                calculated_on: '2024-10-12'
                created_at: '2025-09-27T23:42:29.138Z'
                updated_at: '2025-09-27T23:42:29.138Z'
  "/doctors":
    get:
      summary: list doctors
      tags:
      - Doctor
      parameters:
      - name: offset
        in: query
        required: false
        schema:
          type: number
      - name: limit
        in: query
        required: false
        schema:
          type: number
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                first_name: Jason
                last_name: Hudson
                middle_name: O'Connell
                created_at: '2025-09-27T23:42:29.229Z'
                updated_at: '2025-09-27T23:42:29.229Z'
              - id: 2
                first_name: Theda
                last_name: Block
                middle_name: Thompson
                created_at: '2025-09-27T23:42:29.234Z'
                updated_at: '2025-09-27T23:42:29.234Z'
              - id: 3
                first_name: Hugh
                last_name: Bartell
                middle_name: Daugherty
                created_at: '2025-09-27T23:42:29.237Z'
                updated_at: '2025-09-27T23:42:29.237Z'
              - id: 4
                first_name: Kelly
                last_name: Fritsch
                middle_name: Wisoky
                created_at: '2025-09-27T23:42:29.241Z'
                updated_at: '2025-09-27T23:42:29.241Z'
              - id: 5
                first_name: Josue
                last_name: Simonis
                middle_name: Kunde
                created_at: '2025-09-27T23:42:29.244Z'
                updated_at: '2025-09-27T23:42:29.244Z'
    post:
      summary: create doctor
      tags:
      - Doctor
      parameters: []
      responses:
        '201':
          description: Doctor created successfully
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                middle_name:
                  type: string
              required:
              - first_name
              - last_name
  "/doctors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show doctor
      tags:
      - Doctor
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 6
                first_name: Solomon
                last_name: Fritsch
                middle_name: Hane
                created_at: '2025-09-27T23:42:29.417Z'
                updated_at: '2025-09-27T23:42:29.417Z'
    put:
      summary: update doctor
      tags:
      - Doctor
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                first_name: Charmain
                last_name: Bogan
                middle_name: Luettgen
                id: 6
                created_at: '2025-09-27T23:42:29.501Z'
                updated_at: '2025-09-27T23:42:29.501Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                middle_name:
                  type: string
  "/gender":
    get:
      summary: list genders
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                name: Female
                created_at: '2025-09-27T23:42:29.643Z'
                updated_at: '2025-09-27T23:42:29.643Z'
    post:
      summary: create gender
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                error: 'Error {name: ["Gender name already exists"]}'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gender:
                  type: string
              description: 'gender ex: Male'
  "/patients":
    get:
      summary: list patients
      parameters:
      - name: full_name
        in: query
        schema:
          type: string
      - name: gender
        in: query
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      tags:
      - Patients
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
              - id: 1
                first_name: Val
                last_name: Ondricka
                middle_name: Spinka
                gender_id: 1
                birthday: '1979-10-02'
                height: 137
                weight: '158.72'
                created_at: '2025-09-27T23:42:29.861Z'
                updated_at: '2025-09-27T23:42:29.861Z'
                full_name: val ondricka spinka
                doctors:
                - id: 1
                  first_name: Miranda
                  last_name: Rolfson
                  middle_name: Schmitt
                  created_at: '2025-09-27T23:42:29.864Z'
                  updated_at: '2025-09-27T23:42:29.864Z'
                - id: 2
                  first_name: Tatiana
                  last_name: Frami
                  middle_name: Reilly
                  created_at: '2025-09-27T23:42:29.868Z'
                  updated_at: '2025-09-27T23:42:29.868Z'
                gender:
                  id: 1
                  name: Male
                  created_at: '2025-09-27T23:42:29.857Z'
                  updated_at: '2025-09-27T23:42:29.857Z'
    post:
      summary: Create patient
      tags:
      - Patients
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    birthday:
                      type: string
                      format: date
                    height:
                      type: number
                    weight:
                      type: number
                    gender:
                      type: string
                    doctor_ids:
                      type: array
                      items:
                        type: integer
                  required:
                  - first_name
                  - last_name
                  - birthday
                  - height
                  - weight
                  - gender
  "/patients/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show patient
      tags:
      - Patients
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1
                first_name: Patience
                last_name: Zboncak
                middle_name: Parker
                gender_id: 1
                birthday: '1981-11-11'
                height: 137
                weight: '19.78'
                created_at: '2025-09-27T23:42:30.076Z'
                updated_at: '2025-09-27T23:42:30.076Z'
                full_name: patience zboncak parker
                doctors: []
                gender:
                  id: 1
                  name: Male
                  created_at: '2025-09-27T23:42:30.072Z'
                  updated_at: '2025-09-27T23:42:30.072Z'
    put:
      summary: update patient
      tags:
      - Patients
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                id: 1
                first_name: Иван
                last_name: Петров
                middle_name: Denesik
                gender_id: 1
                birthday: '1990-01-01'
                height: 180
                weight: '75.0'
                created_at: '2025-09-27T23:42:30.149Z'
                updated_at: '2025-09-27T23:42:30.161Z'
                full_name: иван петров denesik
                doctors: []
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
